language: java
before-install:
 - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
 - tar -zxf android-sdk_r20.0.3-linux.tgz
 - export ANDROID_HOME=~/builds/androrm/androrm/android-sdk-linux
 - export PATH=${PATH}:${ANDROID_HOME}:/tools:${ANDROID_HOME}:/platform-tools
 - android update sdk --filter 1,2,9 --no-ui --force
